name: Sandbox
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - name: npmjs
            url: null # npmjs is default.
            token: NPM_TOKEN
          - name: github
            url: "https://npm.pkg.github.com"
            token: GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v2
      - name: echo matrix
        run: "echo ${{ toJSON(matrix.registry) }}"
#       - run: |
#           echo 1
#           test 1 = 2
#           echo 2
