name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: |
          Log level
          ログレベル
        required: true
        # default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        # required: true
      text:
        description: strings
        type: string

jobs:
  log-the-inputs:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-slim
    steps:
      - name: "Run on ${{ github.ref }}"
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "Text: ${{ inputs.text }}"
          echo "Branch: ${{ github.ref }}"
          sleep 60
          echo "Sleeped"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
